### ISSUE TITLE
VS Code Folding

### ISSUE THREAD

**Issue by robertcatgithub** [mallek/vscode-pick-basic-syntax-highlighter#1]
hi Travis, I'm dealing with serious PICK spaghetti codes - do you know if there's a way to have code-folding ?
thanks

**Comment by itsxallwater** [comment]
Some code chunks already support this, i.e.:

```
IF SOMETHING THEN
  STUFF= VALUE
END
```

Or:

```
EOF= 0
LOOP
  READNEXT RID ELSE EOF= 1
UNTIL EOF DO
  READ ITM FROM TEST.FILE,RID ELSE NULL
REPEAT
```

However I'm working on a few nice-to-have modifications to this Extension, including:

1) Support for ! for comments (in addition to *)
2) Fix for false comment detection within strings (ID:"*":SEQ incorrectly flags *":SEQ as a comment)

I added in a proof-of-concept folding definition such that you can define a fold-able section by saying:

```
!REGION
STUFF= MORE.STUFF
!ENDREGION
```

I'm hoping to expand that to also allow a * instead of the !.

**Comment by mallek** [comment]
Feel free to put in a pull request and I’ll test it and push it to the extensions repo.  Thanks for your work on this.

**Comment by itsxallwater** [comment]
Posted. First PR on GitHub for me hopefully that worked okay!
